config/routes.rb
Rails.application.routes.draw do

  root 'root#index'

  put  'update' => 'root#update'
  get  'status' => 'root#check_status'
  post 'status' => 'root#check_status'
  get  'sr'     => 'root#menu',  as: :menu
  get  'notes'  => 'root#notes', as: :notes
  get  'latest' => 'root#latest'
  post 'latest' => 'root#latest'
  put  'cutin'  => 'root#cutin'
  delete  'union_history' => 'root#delete_union_history'

  get    't'                 => 'timeline#index',     as: :timeline
  get    't/d/:date'         => 'timeline#revs',      as: :timeline_revs
  get    't/d/:date/r/:rev'  => 'timeline#situation', as: :timeline_situation
  delete 't/d/:date/r/:rev'  => 'timeline#destroy'
  get    't/d/:date/f/:fort' => 'timeline#fort',      as: :timeline_for_fort
  get    't/d/:date/g/:name' => 'timeline#guild',     as: :timeline_for_guild
  get    't/d/:date/u'       => 'timeline#union_select',   as: :timeline_union
  post   't/d/:date/u'       => 'timeline#union_redirect'
  get    't/d/:date/u/:code' => 'timeline#union',          as: :timeline_for_union
  get    't/span'            => 'timeline#span_union_select',   as: :timeline_span_union_select
  post   't/span'            => 'timeline#span_union_redirect'
  get    't/span/:from-:to/g/:name' => 'timeline#span_guild',   as: :timeline_span_guild
  get    't/span/:from-:to/u/:code' => 'timeline#span_union',   as: :timeline_span_union

  get  'r'                    => 'result#index',   as: :result
  get  'r/rulers/:fort'       => 'result#rulers',  as: :result_rulers
  get  'r/date'               => 'result#dates',   as: :result_dates
  get  'r/date/:date/forts'   => 'result#forts',   as: :result_forts
  get  'r/date/:date/callers' => 'result#callers', as: :result_callers
  get  'r/total'              => 'result#total_select',   as: :result_total
  post 'r/total'              => 'result#total_redirect'
  get  'r/total/rank'         => 'result#total_rank',     as: :result_total_rank
  get  'r/total/g/:name'      => 'result#total_guild',    as: :result_total_guild
  get  'r/total/u/:code'      => 'result#total_union',    as: :result_total_union
  get  'r/recently'              => 'result#recently_select',   as: :result_recently
  post 'r/recently'              => 'result#recently_redirect'
  get  'r/recently/:num/rank'    => 'result#recently_rank',     as: :result_recently_rank
  get  'r/recently/:num/g/:name' => 'result#recently_guild',    as: :result_recently_guild
  get  'r/recently/:num/u/:code' => 'result#recently_union',    as: :result_recently_union
  get  'r/span'                   => 'result#span_select',   as: :result_span
  post 'r/span'                   => 'result#span_redirect'
  get  'r/span/:from-:to/rank'    => 'result#span_rank',     as: :result_span_rank
  get  'r/span/:from-:to/g/:name' => 'result#span_guild',    as: :result_span_guild
  get  'r/span/:from-:to/u/:code' => 'result#span_union',    as: :result_span_union

  get    'a'              => 'admin#index',           as: :admin
  get    'a/login'        => 'admin#login',           as: :admin_login
  post   'a/login'        => 'admin#add_session'
  get    'a/backup'       => 'admin#backup',          as: :admin_backup
  post   'a/backup'       => 'admin#backup_execute'
  get    'a/backup/:rev'  => 'admin#backup_download', as: :admin_backup_file
  delete 'a/backup/:rev'  => 'admin#backup_delete'
  get    'a/result'       => 'admin#result',          as: :admin_result
  post   'a/result'       => 'admin#add_result'
  get    'a/rulers'       => 'admin#rulers',          as: :admin_rulers
  post   'a/rulers'       => 'admin#rulers_new'
  get    'a/rulers/:date' => 'admin#rulers_show',     as: :admin_rulers_data
  put    'a/rulers/:date' => 'admin#rulers_update'
  delete 'a/rulers/:date' => 'admin#rulers_delete'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found' => 'root#not_found', via: [:get, :post, :put, :delete, :patch]
  end

end

app/controllers/result_controller.rb
class ResultController < ApplicationController
  include FortUtil
  include TimeUtil

  before_action :check_time_mode
  before_action :recently_result_action, only: [:recently_rank, :recently_guild, :recently_union]
  before_action :span_result_action, only: [:span_rank, :span_guild, :span_union]
  before_action { add_navs('Result') }

  def index
  end

  def rulers
    @fort = params[:fort]
    (render_404; return) unless fort_groups?(@fort)
    @rulers = Ruler.for_group(@fort)

    add_navs("History of Rulers")
    add_navs(@fort)
  end

  def dates
    list = CacheData.result_dates
    default_size = ServerSettings.data_size_recently

    @dates = case
    when params[:all]
      list
    when params[:recently]
      size = params[:recently].to_i
      redirect_to result_dates_path if (size <= 0 || size == default_size)
      redirect_to result_dates_path(all: 1) if size > list.size
      list.take(size)
    else
      list.take(default_size)
    end

    add_navs_for_date(@dates) if @dates.size == 1
  end

  def forts
    @date = params[:date]
    (render_404; return) unless CacheData.result_dates.include?(@date)
    @rulers = Ruler.for_date(@date)
    @breaks = Caller.where(gvdate: @date).group(:fort_code).count

    add_navs_for_date(@date)
    add_navs("Forts")
  end

  def callers
    @date = params[:date]
    (render_404; return) unless CacheData.result_dates.include?(@date)
    @callers = GuildResult.for_date(@date)

    add_navs_for_date(@date)
    add_navs("Callers")
  end

  def total_select
    @names = CacheData.guild_names_for_select(params[:all])
  end

  def total_redirect
    case
    when params['for-rank']
      redirect_to result_total_rank_path
    when params['for-guild']
      gs = parse_guild_params(params[:guild], CacheData.guild_names_for_all)
      case
      when gs.empty?
        redirect_to result_total_path
      when gs.size == 1
        redirect_to result_total_guild_path(name: encode_for_url(gs.first))
      else
        redirect_to result_total_union_path(code: create_union_code(gs))
      end
    else
      redirect_to result_total_path
    end
  end

  def total_rank
    @callers = GuildResult.totalize

    add_navs("Callers Ranking")
    add_navs("Total")
  end

  def total_guild
    @gname = decode_for_url(params[:name])
    (render_404; return) unless CacheData.guild_names_for_all.include?(@gname)
    @results = GuildResult.for_guild(@gname)
    @total = GuildResult.combine(@results)
    add_union_history(@gname) unless ServerSettings.only_union_history?

    add_navs("Total")
    add_navs_for_guild(@gname)
  end

  def total_union
    @names = parse_union_code(params[:code], CacheData.guild_names_for_all)
    case
    when @names.empty?
      render_404; return
    when @names.size == 1
      redirect_to result_total_guild_path(name: encode_for_url(@names.first))
      return
    end

    @results = @names.map{|g| GuildResult.totalize_for_guild(g)}
    @total = GuildResult.combine(@results)
    add_union_history(@names)

    add_navs("Total")
    add_navs_for_guild(@names)
  end

  def recently_select
    @names = CacheData.guild_names_for_select(params[:all])
  end

  def recently_redirect
    case
    when params['for-rank']
      num = params['recently-rank'].to_i
      (redirect_to result_recently_path; return) unless valid_result_size?(num)
      redirect_to result_recently_rank_path(num: num)
    when params['for-guild']
      num = params['recently-guild'].to_i
      (redirect_to result_recently_path; return) unless valid_result_size?(num)
      gs = parse_guild_params(params[:guild], CacheData.guild_names_for_all)
      case
      when gs.empty?
        redirect_to result_recently_path
      when gs.size == 1
        redirect_to result_recently_guild_path(num: num, name: encode_for_url(gs.first))
      else
        redirect_to result_recently_union_path(num: num, code: create_union_code(gs))
      end
    else
      redirect_to result_recently_path
    end
  end

  def recently_rank
    @callers = GuildResult.totalize(dates: @dates)

    add_navs("Callers Ranking")
    add_navs("Recently #{@dates.size}weeks")
  end

  def recently_guild
    @gname = decode_for_url(params[:name])
    (render_404; return) unless CacheData.guild_names_for_all.include?(@gname)
    @results = GuildResult.for_guild(@gname).for_date(@dates)
    @total = GuildResult.combine(@results)
    add_union_history(@gname) unless ServerSettings.only_union_history?

    add_navs("Recently #{@dates.size}weeks")
    add_navs_for_guild(@gname)
  end

  def recently_union
    @names = parse_union_code(params[:code], CacheData.guild_names_for_all)
    case
    when @names.empty?
      render_404; return
    when @names.size == 1
      redirect_to result_recently_guild_path(num: @dates.size, name: encode_for_url(@names.first))
      return
    end

    @results = @names.map{|g| GuildResult.totalize_for_guild(g, dates: @dates)}
    @total = GuildResult.combine(@results)
    add_union_history(@names)

    add_navs("Recently #{@dates.size}weeks")
    add_navs_for_guild(@names)
  end

  def span_select
    @names = CacheData.guild_names_for_select(params[:all])
    @dates = CacheData.result_dates
  end

  def span_redirect
    case
    when params['for-rank']
      from, to = [params['span-from-rank'], params['span-to-rank']].sort
      (redirect_to result_span_path; return) unless exist_result_gvdates_pair?(from, to)
      redirect_to result_span_rank_path(from: from, to: to)
    when params['for-guild']
      from, to = [params['span-from-guild'], params['span-to-guild']].sort
      (redirect_to result_span_path; return) unless exist_result_gvdates_pair?(from, to)
      gs = parse_guild_params(params[:guild], CacheData.guild_names_for_all)
      case
      when gs.empty?
        redirect_to result_span_path
      when gs.size == 1
        redirect_to result_span_guild_path(from: from, to: to, name: encode_for_url(gs.first))
      else
        redirect_to result_span_union_path(from: from, to: to, code: create_union_code(gs))
      end
    else
      redirect_to result_span_path
    end
  end

  def span_rank
    @callers = GuildResult.totalize(dates: @dates)

    add_navs("Callers Ranking")
    add_navs_for_date(@dates)
  end

  def span_guild
    @gname = decode_for_url(params[:name])
    (render_404; return) unless CacheData.guild_names_for_all.include?(@gname)
    @results = GuildResult.for_guild(@gname).for_date(@dates)
    @total = GuildResult.combine(@results)
    add_union_history(@gname) unless ServerSettings.only_union_history?

    add_navs_for_date(@dates)
    add_navs_for_guild(@gname)
  end

  def span_union
    @names = parse_union_code(params[:code], CacheData.guild_names_for_all)
    case
    when @names.empty?
      render_404; return
    when @names.size == 1
      redirect_to result_span_guild_path(from: @dates.first, to: @dates.last, name: encode_for_url(@names.first))
      return
    end

    @results = @names.map{|g| GuildResult.totalize_for_guild(g, dates: @dates)}
    @total = GuildResult.combine(@results)
    add_union_history(@names)

    add_navs_for_date(@dates)
    add_navs_for_guild(@names)
  end

  private

  def valid_result_size?(num)
    return false unless num
    ServerSettings.data_size_range.include?(num) ? true : false
  end

  def exist_result_gvdates_pair?(from, to)
    return false unless (from && to)
    return false unless (CacheData.result_dates.include?(from) && CacheData.result_dates.include?(to))
    true
  end

  def recently_result_action
    num = params[:num].to_i
    redirect_to result_recently_path unless valid_result_size?(num)
    @dates = CacheData.result_dates.take(num).sort
    redirect_to result_recently_path if @dates.empty?
  end

  def span_result_action
    from = params[:from]
    to = params[:to]
    (render_404; return) unless exist_result_gvdates_pair?(from, to)
    @dates = CacheData.result_dates.select{|d| d >= from}.select{|d| d <= to}.sort
    redirect_to result_span_path unless valid_result_size?(@dates.size)
  end

end

app/helpers/result_helper.rb
module ResultHelper

  def result_view_for_se?
    return false unless params[:priority]
    params[:priority].downcase == 'se' ? true : false
  end

  def result_view_for_fe?
    return false unless params[:priority]
    params[:priority].downcase == 'fe' ? true : false
  end

  def result_view_for_all?
    return true unless params[:priority]
    return false if (result_view_for_se? || result_view_for_fe?)
    true
  end

  def result_subtitle
    case
    when result_view_for_se?
      ' (for SE)'
    when result_view_for_fe?
      ' (for FE)'
    else
      ''
    end
  end

end

app/views/result/_guild_result.erb
<%
size = case
when gvtype_fe?
  12
when gvtype_te?
  6
end
%>
<div class="row">
  <div class="span<%= size %>">
    <h4>Total</h4>
    <table class="table table-condensed">
      <thead>
        <%= render 'result_table_header' %>
      </thead>
      <tbody>
        <%= render 'result_table', result: total, dates: dates, header_type: :total, target: target %>
      </tbody>
    </table>
  </div>
</div>
<% unless results.empty? %>
  <div class="row">
    <div class="span<%= size %>">
      <h4>Dates</h4>
      <table class="table table-condensed">
        <thead>
          <%= render 'result_table_header' %>
        </thead>
        <tbody>
          <% results.sort_by(&:gvdate).reverse.each do |r| %>
            <%= render 'result_table', result: r, dates: dates, header_type: :guild, target: target %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/result/dates.erb
<div class="row">
  <div class="span12">
    <ul class="breadcrumb">
      <%= render 'result_header' %>
      <li class="active"><strong>Result for Date</strong></li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="span6">
    <h3>Result for Date</h3>
  </div>
</div>
<div class="row">
  <div class="span6">
    <p>
      <small>
        <%= link_to("Recent #{data_size_recently}weeks", result_dates_path) %>
        <% if data_size_max > data_size_recently %>
          / <%= link_to("Recent #{data_size_max}weeks", result_dates_path(recently: data_size_max)) %>
        <% end %>
        / <%= link_to("All dates", result_dates_path(all: 1)) %>
      </small>
    </p>
  </div>
</div>
<div class="row">
  <div class="span4">
    <table class="table table-striped table-bordered table-condensed">
      <thead>
        <tr>
          <th>Date</th>
          <th>Forts</th>
          <th>Callers</th>
        </tr>
      </thead>
      <tbody>
        <% @dates.sort.reverse.each do |d| %>
          <tr>
            <td class="span2"><%= divided_date(d) %></td>
            <td class="span1"><%= link_to("Forts", result_forts_path(date: d)) %></td>
            <td class="span1"><%= link_to("Callers", result_callers_path(date: d)) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/result/index.erb
<div class="row">
  <div class="span12">
    <ul class="breadcrumb">
      <%= render 'menu_crumb' %>
      <li class="active"><strong>Result</strong></li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="span6">
    <h3>History of Rulers</h3>
    <ul class="nav nav-tabs nav-stacked">
      <% FortUtil.fort_groups.each do |f| %>
        <li><%= link_to(f, result_rulers_path(fort: f)) %></li>
      <% end %>
    </ul>
    <h3>Result for Date</h3>
    <ul class="nav nav-tabs nav-stacked">
      <li><%= link_to('Dates', result_dates_path) %></li>
    </ul>
    <h3>Result for Guilds</h3>
    <ul class="nav nav-tabs nav-stacked">
      <li><%= link_to('Total', result_total_path) %></li>
      <li><%= link_to('Recently', result_recently_path) %></li>
      <li><%= link_to('Span', result_span_path) %></li>
    </ul>
  </div>
</div>

app/views/result/recently_guild.erb
<% num = @dates.size %>
<div class="row">
  <div class="span12">
    <ul class="breadcrumb">
      <%= render 'result_header' %>
      <li>
        <%= link_to('Recently', result_recently_path) %> <span class="divider">&gt;</span>
      </li>
      <li>
        <%= num %>weeks <span class="divider">&gt;</span>
      </li>
      <li class="active"><strong><%= @gname %></strong></li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="span9">
    <h3>Recently <%= num %>weeks Result : <%= @gname %></h3>
  </div>
</div>
<div class="row">
  <div class="span12">
    <hr/>
  </div>
</div>
<%= render 'guild_result', results: @results, total: @total, dates: @dates, target: :recently %>

app/views/result/recently_rank.erb
<% num = @dates.size %>
<div class="row">
  <div class="span12">
    <ul class="breadcrumb">
      <%= render 'result_header' %>
      <li>
        <%= link_to('Recently', result_recently_path) %> <span class="divider">&gt;</span>
      </li>
      <li>
        <%= num %>weeks <span class="divider">&gt;</span>
      </li>
      <li class="active"><strong>Callers Ranking</strong></li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="span9">
    <h3>Callers Ranking : Recently <%= num %>weeks <%= result_subtitle %></h3>
  </div>
</div>
<% unless gvtype_te? %>
  <div class="row">
    <div class="offset6 span3">
      priority : <%= link_to_unless(result_view_for_all?,  'Total', result_recently_rank_path(num: num)) %>
      / <%= link_to_unless(result_view_for_se?, 'SE', result_recently_rank_path(num: num, priority: 'se')) %>
      / <%= link_to_unless(result_view_for_fe?, 'FE', result_recently_rank_path(num: num, priority: 'fe')) %>
    </div>
  </div>
<% end %>
<div class="row">
  <div class="span9">
    <hr/>
  </div>
</div>
<%= render 'caller_ranking', callers: @callers, dates: @dates, target: :recently %>

app/views/result/recently_union.erb
<% num = @dates.size %>
<div class="row">
  <div class="span12">
    <ul class="breadcrumb">
      <%= render 'result_header' %>
      <li>
        <%= link_to('Recently', result_recently_path) %> <span class="divider">&gt;</span>
      </li>
      <li>
        <%= num %>weeks <span class="divider">&gt;</span>
      </li>
      <li class="active"><strong>Union</strong></li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="span9">
    <h3>Recently <%= num %>weeks Result : Union</h3>
    <ul class="unstyled">
      <li class="union">Guild : </li>
      <% @names.each do |n| %>
        <li class="union">
          <%= link_to(n, result_recently_guild_path(num: num, name: encode_for_url(n))) %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<div class="row">
  <div class="span12">
    <hr/>
  </div>
</div>
<%= render 'union_result', results: @results, total: @total, dates: @dates, target: :recently %>

app/views/result/rulers.erb
<div class="row">
  <div class="span12">
    <ul class="breadcrumb">
      <%= render 'result_header' %>
      <li>
        History of Rulers <span class="divider">&gt;</span>
      </li>
      <li class="active"><strong><%= @fort %></strong></li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="span8">
    <h3>History of Rulers : <%= @fort %></h3>
  </div>
  <div class="span4">
    ↓↓↓：Full Defense (no called) / ↓：Get Again
  </div>
</div>
<% forts = FortUtil.fort_codes_for(@fort) %>
<div class="row">
  <div class="span12">
    <table class="table-bordered">
      <thead>
        <tr>
          <th class="span2">Dates</th>
          <% forts.each do |fid| %>
            <th class="span3"><%= fid %></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <%
        rtable = @rulers.inject({}){|h, r| h["#{r.gvdate}_#{r.fort_code}"] = r; h}
        dates = @rulers.map(&:gvdate).uniq.sort
        linked = {}
        before = {}
        dates.each do |date|
        %>
          <tr>
            <td class="span2 text-center">
              <%= link_to(divided_date(date), result_forts_path(date)) %>
            </td>
            <% 
            forts.each do |fcd|
              r = rtable["#{date}_#{fcd}"]
              case
              when r.nil? %>
                <td class="span3 text-center"><small>-</small></td>
              <% when r.full_defense %>
                <td class="span3 text-center ruled-stay"><small>↓↓↓</small></td>
              <% else %>
                <% name = r.guild_name
                if before[fcd] == name %>
                  <td class="span3 text-center ruled-again"><small>↓</small></td>
                <% else %>
                  <% if linked[name] %>
                    <td class="span3 text-center"><%= name %></td>
                  <% else
                    linked[name] = true %>
                    <td class="span3 text-center">
                      <%= link_to(name, result_total_guild_path(name: encode_for_url(name))) %>
                    </td>
                  <% end %>
                <% end %>
                <% before[fcd] = name %>
              <% end %>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/result/span_guild.erb
<%
from = @dates.first
to = @dates.last
span_label = format_span(from, to)
%>
<div class="row">
  <div class="span12">
    <ul class="breadcrumb">
      <%= render 'result_header' %>
      <li>
        <%= link_to('Span', result_span_path) %> <span class="divider">&gt;</span>
      </li>
      <li>
        <%= span_label %> <span class="divider">&gt;</span>
      </li>
      <li class="active"><strong><%= @gname %></strong></li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="span12">
    <h3><%= span_label %> (<%= @dates.size %>weeks) Result : <%= @gname %></h3>
  </div>
</div>
<div class="row">
  <div class="span12">
    <hr/>
  </div>
</div>
<%= render 'guild_result', results: @results, total: @total, dates: @dates, target: :span %>

app/views/result/span_rank.erb
<%
from = @dates.first
to = @dates.last
span_label = format_span(from, to)
%>
<div class="row">
  <div class="span12">
    <ul class="breadcrumb">
      <%= render 'result_header' %>
      <li>
        <%= link_to('Span', result_span_path) %> <span class="divider">&gt;</span>
      </li>
      <li>
        <%= span_label %> <span class="divider">&gt;</span>
      </li>
      <li class="active"><strong>Callers Ranking</strong></li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="span9">
    <h3>Callers Ranking : <%= span_label %> (<%= @dates.size %>weeks) <%= result_subtitle %></h3>
  </div>
</div>
<% unless gvtype_te? %>
  <div class="row">
    <div class="offset6 span3">
      priority : <%= link_to_unless(result_view_for_all?,  'Total', result_span_rank_path(from: from, to: to)) %>
      / <%= link_to_unless(result_view_for_se?, 'SE', result_span_rank_path(from: from, to: to, priority: 'se')) %>
      / <%= link_to_unless(result_view_for_fe?, 'FE', result_span_rank_path(from: from, to: to, priority: 'fe')) %>
    </div>
  </div>
<% end %>
<div class="row">
  <div class="span9">
    <hr/>
  </div>
</div>
<%= render 'caller_ranking', callers: @callers, dates: @dates, target: :span %>

app/views/result/span_select.erb
<%
from_default = @dates[ServerSettings.data_size_recently - 1]
result_range = ServerSettings.data_size_range
%>
<div class="row">
  <div class="span12">
    <ul class="breadcrumb">
      <%= render 'result_header' %>
      <li class="active"><strong>Span</strong></li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="span6">
    <h3>Span Result</h3>
  </div>
</div>
<%= form_tag(result_span_path, method: :post, class: 'form-inline') do %>
  <div class="row">
    <div class="span6">
      <legend>Callers Ranking</legend>
      <div class="form-actions">
        <label class="control-label" for="span-from-rank">from : </label>
        <select id="span-from-all" name="span-from-rank" class="span2">
          <% @dates.each do |d| %>
            <option value="<%= d %>"<%= ' selected' if d == from_default %>><%= divided_date(d) %></option>
          <% end %>
        </select>
        <label class="control-label" for="span-to-rank">to : </label>
        <select id="span-to-all" name="span-to-rank" class="span2">
          <% @dates.each do |d| %>
            <option value="<%= d %>"><%= divided_date(d) %></option>
          <% end %>
        </select>
        <button type="submit" class="btn btn-primary" name="for-rank" value="1">View</button>
        <p><small>min : <%= result_range.min %>weeks / max : <%= result_range.max %>weeks</small></p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="span6">
      <legend>Select Guild or Union</legend>
      <p>
        <small>
          <% if params[:all] %>
            <u>From : All</u>
            (<%= link_to('Select from Recently Guilds', result_span_path) %>)
          <% else %>
            <u>From : Recently <%= ServerSettings.data_size_recently %>weeks</u>
            (<%= link_to('Select from All Guilds', result_span_path(all: 1)) %>)
          <% end %>
        </small>
      </p>
      <%= render 'guild_select', opts: create_option_from_names(@names) %>
      <div class="form-actions">
        <label class="control-label" for="span-from-guild">from : </label>
        <select id="span-from-guild" name="span-from-guild" class="span2">
          <% @dates.each do |d| %>
            <option value="<%= d %>"<%= ' selected' if d == from_default %>><%= divided_date(d) %></option>
          <% end %>
        </select>
        <label class="control-label" for="span-to-guild">to : </label>
        <select id="span-to-guild" name="span-to-guild" class="span2">
          <% @dates.each do |d| %>
            <option value="<%= d %>"><%= divided_date(d) %></option>
          <% end %>
        </select>
        <button type="submit" class="btn btn-primary" name="for-guild" value="1">View</button>
        <p><small>min : <%= result_range.min %>weeks / max : <%= result_range.max %>weeks</small></p>
      </div>
    </div>
    <%= render 'union_history' %>
  </div>
<% end %>

app/views/result/span_union.erb
<%
from = @dates.first
to = @dates.last
span_label = format_span(from, to)
%>
<div class="row">
  <div class="span12">
    <ul class="breadcrumb">
      <%= render 'result_header' %>
      <li>
        <%= link_to('Span', result_span_path) %> <span class="divider">&gt;</span>
      </li>
      <li>
        <%= span_label %> <span class="divider">&gt;</span>
      </li>
      <li class="active"><strong>Union</strong></li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="span9">
    <h3><%= span_label %> (<%= @dates.size %>weeks) Result : Union</h3>
    <ul class="unstyled">
      <li class="union">Guild : </li>
      <% @names.each do |n| %>
        <li class="union">
          <%= link_to(n, result_span_guild_path(from: from, to: to, name: encode_for_url(n))) %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<div class="row">
  <div class="span12">
    <hr/>
  </div>
</div>
<%= render 'union_result', results: @results, total: @total, dates: @dates, target: :span %>

app/views/result/total_guild.erb
<div class="row">
  <div class="span12">
    <ul class="breadcrumb">
      <%= render 'result_header' %>
      <li>
        <%= link_to('Total', result_total_path) %> <span class="divider">&gt;</span>
      </li>
      <li class="active"><strong><%= @gname %></strong></li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="span9">
    <h3>Total Result : <%= @gname %></h3>
  </div>
</div>
<div class="row">
  <div class="span12">
    <hr/>
  </div>
</div>
<%= render 'guild_result', results: @results, total: @total, dates: [], target: :total %>