config/routes.rb
Rails.application.routes.draw do

  root 'root#index'

  put  'update' => 'root#update'
  get  'status' => 'root#check_status'
  post 'status' => 'root#check_status'
  get  'sr'     => 'root#menu',  as: :menu
  get  'notes'  => 'root#notes', as: :notes
  get  'latest' => 'root#latest'
  post 'latest' => 'root#latest'
  put  'cutin'  => 'root#cutin'
  delete  'union_history' => 'root#delete_union_history'

  get    't'                 => 'timeline#index',     as: :timeline
  get    't/d/:date'         => 'timeline#revs',      as: :timeline_revs
  get    't/d/:date/r/:rev'  => 'timeline#situation', as: :timeline_situation
  delete 't/d/:date/r/:rev'  => 'timeline#destroy'
  get    't/d/:date/f/:fort' => 'timeline#fort',      as: :timeline_for_fort
  get    't/d/:date/g/:name' => 'timeline#guild',     as: :timeline_for_guild
  get    't/d/:date/u'       => 'timeline#union_select',   as: :timeline_union
  post   't/d/:date/u'       => 'timeline#union_redirect'
  get    't/d/:date/u/:code' => 'timeline#union',          as: :timeline_for_union
  get    't/span'            => 'timeline#span_union_select',   as: :timeline_span_union_select
  post   't/span'            => 'timeline#span_union_redirect'
  get    't/span/:from-:to/g/:name' => 'timeline#span_guild',   as: :timeline_span_guild
  get    't/span/:from-:to/u/:code' => 'timeline#span_union',   as: :timeline_span_union

  get  'r'                    => 'result#index',   as: :result
  get  'r/rulers/:fort'       => 'result#rulers',  as: :result_rulers
  get  'r/date'               => 'result#dates',   as: :result_dates
  get  'r/date/:date/forts'   => 'result#forts',   as: :result_forts
  get  'r/date/:date/callers' => 'result#callers', as: :result_callers
  get  'r/total'              => 'result#total_select',   as: :result_total
  post 'r/total'              => 'result#total_redirect'
  get  'r/total/rank'         => 'result#total_rank',     as: :result_total_rank
  get  'r/total/g/:name'      => 'result#total_guild',    as: :result_total_guild
  get  'r/total/u/:code'      => 'result#total_union',    as: :result_total_union
  get  'r/recently'              => 'result#recently_select',   as: :result_recently
  post 'r/recently'              => 'result#recently_redirect'
  get  'r/recently/:num/rank'    => 'result#recently_rank',     as: :result_recently_rank
  get  'r/recently/:num/g/:name' => 'result#recently_guild',    as: :result_recently_guild
  get  'r/recently/:num/u/:code' => 'result#recently_union',    as: :result_recently_union
  get  'r/span'                   => 'result#span_select',   as: :result_span
  post 'r/span'                   => 'result#span_redirect'
  get  'r/span/:from-:to/rank'    => 'result#span_rank',     as: :result_span_rank
  get  'r/span/:from-:to/g/:name' => 'result#span_guild',    as: :result_span_guild
  get  'r/span/:from-:to/u/:code' => 'result#span_union',    as: :result_span_union

  get    'a'              => 'admin#index',           as: :admin
  get    'a/login'        => 'admin#login',           as: :admin_login
  post   'a/login'        => 'admin#add_session'
  get    'a/backup'       => 'admin#backup',          as: :admin_backup
  post   'a/backup'       => 'admin#backup_execute'
  get    'a/backup/:rev'  => 'admin#backup_download', as: :admin_backup_file
  delete 'a/backup/:rev'  => 'admin#backup_delete'
  get    'a/result'       => 'admin#result',          as: :admin_result
  post   'a/result'       => 'admin#add_result'
  get    'a/rulers'       => 'admin#rulers',          as: :admin_rulers
  post   'a/rulers'       => 'admin#rulers_new'
  get    'a/rulers/:date' => 'admin#rulers_show',     as: :admin_rulers_data
  put    'a/rulers/:date' => 'admin#rulers_update'
  delete 'a/rulers/:date' => 'admin#rulers_delete'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found' => 'root#not_found', via: [:get, :post, :put, :delete, :patch]
  end

end

app/views/admin/_admin_header.erb
<%= render 'menu_crumb' %>
<li>
  <%= link_to('管理メニュー', admin_path) %> <span class="divider">&gt;</span>
</li>

app/views/admin/backup.erb
<div class="row">
  <div class="span12">
    <ul class="breadcrumb">
      <%= render 'admin_header' %>
      <li class="active"><strong>データバックアップ</strong></li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="span6">
    <h3>データバックアップ</h3>
  </div>
</div>
<div class="row">
  <div class="span4">
    <% if flash[:error] %>
      <div class="alert alert-error">
        <p>
          <strong><%= flash[:error] %></strong>
        </p>
      </div>
    <% else %>
      <br/>
    <% end %>
  </div>
  <div class="span2">
    <%= form_tag(admin_backup_path, method: :post) do %>
      <button type="submit" class="btn-mini btn-info">Start Backup</button>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="span6">
    <table class="table table-striped table-condensed">
      <tbody>
        <% @files.sort_by(&:revision).reverse.each do |d| %>
          <tr>
            <td class="span4">
              <%= link_to(d.dump_time, admin_backup_file_path(rev: d.revision)) %>
            </td>
            <td class="span2">
              <%= form_tag(admin_backup_file_path(rev: d.revision), method: :delete) do %>
                <button type="submit" class="btn-mini btn-danger">Delete</button>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/index.erb
<div class="row">
  <div class="span12">
    <ul class="breadcrumb">
      <%= render 'menu_crumb' %>
      <li>
        管理メニュー
      </li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="span6">
    <h3>管理メニュー</h3>
    <ul class="nav nav-tabs nav-stacked">
      <li><%= link_to('データバックアップ', admin_backup_path) %></li>
      <li><%= link_to('結果集計管理', admin_result_path) %></li>
      <li><%= link_to('手動結果入力', admin_rulers_path) %></li>
    </ul>
  </div>
</div>

app/views/admin/login.erb
<div class="row">
  <div class="span12">
    <ul class="breadcrumb">
      <%= render 'menu_crumb' %>
      <li>login</li>
    </ul>
  </div>
</div>
<% error = flash[:error] %>
<div class="row">
  <div class="offset4 span4">
    <%= form_tag(admin_login_path, method: :post, class: 'well') do %>
      <fieldset class="control-group<%= ' error' if error %>">
        <label><%= error || 'ログイン情報を入力してください' %></label>
        <label>user</label>
        <input type="text" name="user" value="" />
        <label>pass</label>
        <input type="password" name="password" value="" />
      </fieldset>
      <button type="submit" class="btn">Login</button> or return to <%= link_to('Strategy Room', menu_path)  %>
    <% end %>
  </div>
</div>

app/views/admin/result.erb
<div class="row">
  <div class="span12">
    <ul class="breadcrumb">
      <%= render 'admin_header' %>
      <li class="active"><strong>結果集計管理</strong></li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="span6">
    <h3>結果追加</h3>
    <p>
      <small>
        コール回数等、結果データ確認用のデータを生成<br />
        通常はGv後に「未集計の全データを集計」を実行すればOK<br />
        集計を自動化したい場合は"bin/add/add_total.rb"をcronで定時実行
      </small>
    </p>
  </div>
</div>
<div class="row">
  <div class="span6">
    <% case
    when flash[:error] %>
      <div class="alert alert-error">
        <p>
          <strong><%= flash[:error] %></strong>
        </p>
      </div>
    <% when flash[:info] %>
      <div class="alert alert-success">
        <p>
          <%= flash[:info] %>
        </p>
      </div>
    <% else %>
      <br/>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="offset3 span3">
    <%= form_tag(admin_result_path, method: :post) do %>
      <button type="submit" class="btn-mini btn-primary">未集計の全データを集計</button>
    <% end %>
  </div>
</div>
<div class="row">
  <%= form_tag(admin_result_path, method: :post) do %>
    <div class="span3">
      <select id="add-date" name="add-date">
        <% @dates.each do |d| %>
          <option value="<%= d %>"><%= divided_date(d) %></option>
        <% end %>
      </select>
    </div>
    <div class="span3">
      <button type="submit" class="btn-mini btn-info">指定した日のデータを集計</button>
    </div>
  <% end %>
</div>

app/views/admin/rulers.erb
<%
now = DateTime.now
now_y = now.year
now_m = now.month
now_d = now.day
years = ((now_y-2)..(now_y+1)).to_a.reverse
%>
<div class="row">
  <div class="span12">
    <ul class="breadcrumb">
      <%= render 'admin_header' %>
      <li class="active"><strong>結果手動入力</strong></li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="span6">
    <h3>結果手動入力</h3>
  </div>
</div>
<div class="row">
  <div class="span4">
    <% case
    when flash[:error] %>
      <div class="alert alert-error">
        <p>
          <strong><%= flash[:error] %></strong>
        </p>
      </div>
    <% when flash[:info] %>
      <div class="alert alert-success">
        <p>
          <%= flash[:info] %>
        </p>
      </div>
    <% else %>
      <br/>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="span6">
    <%= form_tag(admin_rulers_path, method: :post, class: 'form-inline well') do %>
      <select class="input-medium" name="year">
        <% years.each do |y| %>
          <% if y == now_y %>
            <option value="<%= y %>" selected><%= y %></option>
          <% else %>
            <option value="<%= y %>"><%= y %></option>
          <% end %>
        <% end %>
      </select>年
      <select class="input-mini" name="month">
        <% (1..12).each do |m| %>
          <% if m == now_m %>
            <option value="<%= m %>" selected><%= m %></option>
          <% else %>
            <option value="<%= m %>"><%= m %></option>
          <% end %>
        <% end %>
      </select>月
      <select class="input-mini" name="day">
        <% (1..31).each do |d| %>
          <% if d == now_d %>
            <option value="<%= d %>" selected><%= d %></option>
          <% else %>
            <option value="<%= d %>"><%= d %></option>
          <% end %>
        <% end %>
      </select>日
      <button type="submit" class="btn btn-primary">詳細入力</button>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="span6">
    <table class="table table-striped table-bordered table-condensed">
      <thead>
        <tr>
          <th class="span2">Date</th>
          <th class="span1">Type</th>
          <td class="span3">
            <% if params[:all] %>
              <%= link_to('手動入力日のみ表示', admin_rulers_path) %>
            <% else %>
              <%= link_to('自動集計日も表示', admin_rulers_path(all: 1)) %>
            <% end %>
          </td>
        </tr>
      </thead>
      <tbody>
        <% @dates.sort.reverse.each do |d| %>
          <% next unless (params[:all] || @manuals.include?(d)) %>
          <tr>
            <td><%= divided_date(d) %></td>
            <% if @manuals.include?(d) %>
              <td>手動</td>
              <td>
                <%= link_to('Update', admin_rulers_data_path(date: d), class: 'btn btn-primary') %>
              </td>
            <% else %>
              <td>自動</td>
              <td>
                <%= link_to('View', admin_rulers_data_path(date: d), class: 'btn') %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/rulers_show.erb
<%
date = Date.parse(@date)
case
when gvtype_fe?
  valid = date.sunday? ? true : false
  dname = '日曜日'
when gvtype_te?
  valid = date.saturday? ? true : false
  dname = '土曜日'
end

forts = @rulers.inject({}){|h, r| h[r.fort_code] = r; h}
@manuals.each do |m|
  next if forts[m.fort_code]
  forts[m.fort_code] = m
end
manual = @rulers.empty? ? true : false
%>

<div class="row">
  <div class="span12">
    <ul class="breadcrumb">
      <%= render 'admin_header' %>
      <li>
        <%= link_to('結果手動入力', admin_rulers_path) %> <span class="divider">&gt;</span>
      </li>
      <li class="active"><strong><%= divided_date(@date) %></strong></li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="span6">
    <h3>結果手動入力 : <%= divided_date(@date) %></h3>
  </div>
</div>
<div class="row">
  <div class="span6">
    <% case
    when flash[:error] %>
      <div class="alert alert-error">
        <p>
          <strong><%= flash[:error] %></strong>
        </p>
      </div>
    <% when flash[:info] %>
      <div class="alert alert-success">
        <p>
          <%= flash[:info] %>
        </p>
      </div>
    <% when !manual %>
      <div class="alert">
        <p>
          自動集計された結果は手動で修正できません
        </p>
      </div>
    <% when manual && !valid %>
      <div class="alert">
        <p>
          <strong><%= divided_date(@date) %></strong>は<%= dname %>ではありません<br/>
          誤って指定した場合は<%= link_to('戻って選び直してください', admin_rulers_path) %>
        </p>
      </div>
    <% else %>
      <br/>
    <% end %>
  </div>
  <div class="offset5 span1">
    <% if manual %>
      <p>
        <a href="#delete" role="button" class="btn btn-danger" data-toggle="modal">Delete</a>
      </p>
      <div id="delete" class="modal hide fade">
        <div class="modal-header">
          <h3>手動入力データ削除</h3>
        </div>
        <div class="modal-body">
          <p>
            手動入力した結果を削除します。よろしいですか？
          </p>
        </div>
        <div class="modal-footer">
          <%= form_tag(admin_rulers_data_path(date: @date), method: :delete, class: 'form-inline') do %>
            <button type="button" class="btn" data-dismiss="modal" aria-hidden="true">キャンセル</button>
            <button type="submit" class="btn btn-danger">削除</button>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= form_tag(admin_rulers_data_path(date: @date), method: :put, class: 'form-inline') do %>
  <div class="row">
    <div class="span12">
      <table class="table-striped table-bordered">
        <thead>
          <tr>
            <th class="span2"><br/></th>
            <% fort_nums.each do |num| %>
              <th class="span3"><%= num %></th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% fort_groups.each do |g| %>
            <tr>
              <th class="span2"><%= g %></th>
              <% fort_nums.each do |num|
                fcd = "#{g}#{num}"
                r = forts[fcd] %>
                <td class="span3">
                  <% if manual %>
                    <input type="text" class="input-medium" name="<%= "gname[#{fcd}]" %>" value="<%= r ? r.guild_name : '' %>"/>
                  <% else %>
                    <p>
                      <%= ((r.nil? || r.guild_name.blank?) ? '-' : r.guild_name) %>
                    </p>
                  <% end %>
                </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <br/>
  <div class="row">
    <div class="offset5 span3">
      <% if manual %>
        <button type="submit" class="btn btn-primary">更新</button>
      <% else %>
        <button class="btn disabled" disabled>更新</button>
      <% end %>
      <%= link_to('戻る', admin_rulers_path, class: 'btn btn-info') %>
    </div>
  </div>
<% end %>