config/routes.rb
Rails.application.routes.draw do

  root 'root#index'

  put  'update' => 'root#update'
  get  'status' => 'root#check_status'
  post 'status' => 'root#check_status'
  get  'sr'     => 'root#menu',  as: :menu
  get  'notes'  => 'root#notes', as: :notes
  get  'latest' => 'root#latest'
  post 'latest' => 'root#latest'
  put  'cutin'  => 'root#cutin'
  delete  'union_history' => 'root#delete_union_history'

  get    't'                 => 'timeline#index',     as: :timeline
  get    't/d/:date'         => 'timeline#revs',      as: :timeline_revs
  get    't/d/:date/r/:rev'  => 'timeline#situation', as: :timeline_situation
  delete 't/d/:date/r/:rev'  => 'timeline#destroy'
  get    't/d/:date/f/:fort' => 'timeline#fort',      as: :timeline_for_fort
  get    't/d/:date/g/:name' => 'timeline#guild',     as: :timeline_for_guild
  get    't/d/:date/u'       => 'timeline#union_select',   as: :timeline_union
  post   't/d/:date/u'       => 'timeline#union_redirect'
  get    't/d/:date/u/:code' => 'timeline#union',          as: :timeline_for_union
  get    't/span'            => 'timeline#span_union_select',   as: :timeline_span_union_select
  post   't/span'            => 'timeline#span_union_redirect'
  get    't/span/:from-:to/g/:name' => 'timeline#span_guild',   as: :timeline_span_guild
  get    't/span/:from-:to/u/:code' => 'timeline#span_union',   as: :timeline_span_union

  get  'r'                    => 'result#index',   as: :result
  get  'r/rulers/:fort'       => 'result#rulers',  as: :result_rulers
  get  'r/date'               => 'result#dates',   as: :result_dates
  get  'r/date/:date/forts'   => 'result#forts',   as: :result_forts
  get  'r/date/:date/callers' => 'result#callers', as: :result_callers
  get  'r/total'              => 'result#total_select',   as: :result_total
  post 'r/total'              => 'result#total_redirect'
  get  'r/total/rank'         => 'result#total_rank',     as: :result_total_rank
  get  'r/total/g/:name'      => 'result#total_guild',    as: :result_total_guild
  get  'r/total/u/:code'      => 'result#total_union',    as: :result_total_union
  get  'r/recently'              => 'result#recently_select',   as: :result_recently
  post 'r/recently'              => 'result#recently_redirect'
  get  'r/recently/:num/rank'    => 'result#recently_rank',     as: :result_recently_rank
  get  'r/recently/:num/g/:name' => 'result#recently_guild',    as: :result_recently_guild
  get  'r/recently/:num/u/:code' => 'result#recently_union',    as: :result_recently_union
  get  'r/span'                   => 'result#span_select',   as: :result_span
  post 'r/span'                   => 'result#span_redirect'
  get  'r/span/:from-:to/rank'    => 'result#span_rank',     as: :result_span_rank
  get  'r/span/:from-:to/g/:name' => 'result#span_guild',    as: :result_span_guild
  get  'r/span/:from-:to/u/:code' => 'result#span_union',    as: :result_span_union

  get    'a'              => 'admin#index',           as: :admin
  get    'a/login'        => 'admin#login',           as: :admin_login
  post   'a/login'        => 'admin#add_session'
  get    'a/backup'       => 'admin#backup',          as: :admin_backup
  post   'a/backup'       => 'admin#backup_execute'
  get    'a/backup/:rev'  => 'admin#backup_download', as: :admin_backup_file
  delete 'a/backup/:rev'  => 'admin#backup_delete'
  get    'a/result'       => 'admin#result',          as: :admin_result
  post   'a/result'       => 'admin#add_result'
  get    'a/rulers'       => 'admin#rulers',          as: :admin_rulers
  post   'a/rulers'       => 'admin#rulers_new'
  get    'a/rulers/:date' => 'admin#rulers_show',     as: :admin_rulers_data
  put    'a/rulers/:date' => 'admin#rulers_update'
  delete 'a/rulers/:date' => 'admin#rulers_delete'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found' => 'root#not_found', via: [:get, :post, :put, :delete, :patch]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  unless ServerSettings.sample_mode?
    http_basic_authenticate_with(ServerSettings.basic_auth_params)
  end

  unless Rails.application.config.consider_all_requests_local
    rescue_from Exception, with: :server_error
  end

  helper_method :sample_mode?, :view_mode?, :updatable_mode?, :encode_for_url,
    :union_history, :create_union_code, :time_lock_mode?, :time_locked?

  private

  def title_navs
    @title_navs ||= []
    @title_navs
  end

  def add_navs(nav)
    return if nav.blank?
    title_navs << nav
  end

  def add_navs_for_date(date)
    ds = [date].flatten.reject(&:blank?)
    return if ds.empty?

    nav = if ds.size == 1
      divided_date(date)
    else
      "#{divided_date(ds.first)}-#{divided_date(ds.last)}"
    end
    add_navs(nav)
  end

  def add_navs_for_revision(rev)
    return if rev.blank?
    add_navs(revision_to_formet_time(rev))
  end

  def add_navs_for_guild(guild)
    gs = [guild].flatten.reject(&:blank?)
    return if gs.empty?
    nav = if gs.size == 1
      guild
    else
      "#{gs.size}Guilds (#{gs.join(', ')})"
    end
    add_navs(nav)
  end

  def render_404
    render 'root/not_found', status: 404
  end

  def render_locked
    render 'root/locked', status: 403
  end

  def sample_mode?
    ServerSettings.sample_mode? ? true : false
  end

  def view_mode?
    ServerSettings.view_mode? ? true : false
  end

  def updatable_mode?
    return false if sample_mode?
    view_mode? ? false : true
  end

  def time_lock_mode?
    return false unless sample_mode?
    ServerSettings.time_lock? ? true : false
  end

  def time_locked?
    return false unless time_lock_mode?
    return true if Rails.env.development?
    TimeUtil.in_battle_time? ? true : false
  end

  def encode_for_url(s)
    URI.encode_www_form_component(s.gsub('.', '%2e')).gsub('+', '%20')
  end

  def decode_for_url(s)
    URI.decode_www_form_component(s.gsub('%20', '+')).gsub('%2e', '.')
  end

  def encode_base64_for_url(s)
    begin
      Base64.urlsafe_encode64(s)
    rescue
      ''
    end
  end

  def decode_base64_for_url(s)
    begin
      Base64.urlsafe_decode64(s).force_encoding('UTF-8')
    rescue
      ''
    end
  end

  def parse_guild_params(gname, names)
    return [] if gname.nil? || gname.empty? || names.empty?
    [gname].flatten.uniq.reject(&:blank?).select{|n| names.include?(n)}
  end

  def parse_union_code(code, names)
    return [] if code.nil? || code.empty? || names.empty?
    code.split(/,/).uniq.reject(&:blank?).map{|s| decode_base64_for_url(s)}.select{|g| names.include?(g)}
  end

  def create_union_code(gs)
    [gs].flatten.uniq.reject(&:blank?).map{|n| encode_base64_for_url(n)}.flatten.join(',')
  end

  def server_error
    Rails.logger.error($!)
    render template: 'root/error', status: 500
  end

  def add_union_history(guilds)
    gs = [guilds].flatten.uniq.compact
    return if gs.empty?
    orgs = union_history(raw: true)
    str = gs.join("\t")
    orgs.delete(str)
    orgs << str
    size = ServerSettings.union_history_size
    list = orgs.size > size ? orgs.reverse.take(size).reverse : orgs
    set_union_history(list)
  end

  def set_union_history(list)
    val = (list || []).to_json
    cookie_params = {
      value: val,
      expires: 14.days.from_now
    }
    cookie_params[:path] = ServerSettings.app_path unless ServerSettings.app_path.blank?
    cookies[:union_history] = cookie_params
  end

  def reset_union_history
    cookie_params = {
      value: '',
      expires: Time.at(0)
    }
    cookie_params[:path] = ServerSettings.app_path unless ServerSettings.app_path.blank?
    cookies[:union_history] = cookie_params
  end

  def union_history(raw: false)
    begin
      return [] unless cookies[:union_history]
      list = JSON.parse(cookies[:union_history])
      return list if raw
      list.map{|str| str.split("\t")}
    rescue
      []
    end
  end

  def check_time_mode
    (render_locked; return) if time_locked?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include TimeUtil
  include FortUtil

  def site_title
    ServerSettings.site_title
  end

  def site_sub_title
    ServerSettings.site_sub_title
  end

  def title_navs
    return if @title_navs.blank?
    [@title_navs].flatten.reject(&:blank?).reverse.inject(""){|s, n| s << "#{n} | " }
  end

  def data_size_recently
    ServerSettings.data_size_recently
  end

  def data_size_min
    ServerSettings.data_size_min
  end

  def data_size_max
    ServerSettings.data_size_max
  end

  def create_option_from_names(names)
    opts = "<option value=''>-</option>"
    (names || []).sort.each do |n|
      opts << "<option value='#{h(n)}'>#{h(n)}</option>"
    end
    opts
  end

  def create_name_table(names)
    ns = [names].flatten.uniq.compact
    return {} if ns.empty?

    h = {}
    if ns.size == 1
      h[ns.first] = '★'
    else
      ch = 'A'
      ns.each do |n|
        h[n] = ch
        ch = ch.succ
      end
    end

    h
  end

  def adsense
    path = File.join(Rails.root, 'tmp', 'adsence.txt')
    return '' unless File.exist?(path)
    File.read(path)
  end

  def analytics
    path = File.join(Rails.root, 'tmp', 'analytics.txt')
    return '' unless File.exist?(path)
    File.read(path)
  end

  def amazon
    path = File.join(Rails.root, 'tmp', 'amazon.txt')
    return '' unless File.exist?(path)
    File.read(path)
  end

end

app/views/application/_forts_table.erb
<div class="row">
  <div class="span12">
    <table class="table-striped table-bordered">
      <thead>
        <tr>
          <th class="span2"><br/></th>
          <th class="span3">1</th>
          <th class="span3">2</th>
          <th class="span3">3</th>
          <th class="span3">4</th>
          <th class="span3">5</th>
        </tr>
      </thead>
      <tbody>
        <% forts = situation.forts_map
        sup_time = (@gvtime ? @gvtime : situation.update_time)
        fort_groups.each do |g| %>
          <tr>
            <th class="span2"><%= g %></th>
            <% fort_nums.each do |num| %>
              <%
              f = forts["#{g}#{num}"]
              if f
                uptime = f.uptime_from(sup_time) / 60
                upweek = uptime / 10080
                bcount = (@breaks || {})[f.fort_code] || 0
              %>
                <td class="span3">
                  <p>
                    <% if unlink %>
                      <small class="muted"><%= ServerSettings.gvtype_te? ? f.formal_name : f.fort_name %></small><br/>
                    <% else %>
                      <small class="muted">
                        <%= link_to(f.fort_name, timeline_for_fort_path(date: situation.gvdate, fort: g)) %>
                      </small><br/>
                      <small class="muted"><%= f.formal_name %></small><br/>
                    <% end %>
                    <% if f.hot?(sup_time) %>
                      <strong><span class="attention"><%= f.guild_name %></span></strong>
                    <% else %>
                      <strong><%= f.guild_name %></strong>
                    <% end %>
                    <% unless unlink %>
                      <small class="muted">
                        <%= link_to '★', timeline_for_guild_path(date: situation.gvdate, name: encode_for_url(f.guild_name)) %>
                      </small>
                    <% end %>
                    <br/>
                    <% if upweek > 0 %>
                      <small class="muted">uptime:<span class="uptime-attention"><%= upweek %>week!!</span></small>
                    <% else %>
                      <small class="muted">uptime:<%= uptime %>min</small>
                    <% end %>
                    <small class="muted"> / </small>
                    <% if bcount < 3 %>
                      <small class="muted attention"><%= bcount %>-break!!</small>
                    <% else %>
                      <small class="muted"><%= bcount %>-break!!</small>
                    <% end %>
                  </p>
                </td>
              <% else %>
                <td class="span3">-</td>
              <% end %>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/application/_guild_select.erb
<% (1..8).each do |i| %>
  <div class="control-group">
    <label class="control-label" for="guild_<%= i %>">Guild <%= i %></label>
    <div class="controls">
      <select id="guild_<%= i %>" name="guild[]">
        <%= raw opts %>
      </select>
    </div>
  </div>
<% end %>
<a href="#" id="guild-clear" class="btn">Clear Guilds</a>

app/views/application/_guild_timeline.erb
<div class="row">
  <div class="span<%= timeline_span_size %>">
    <table class="table-bordered table-condensed">
      <thead>
        <tr>
          <th class="span2"><%= divided_date(date) %></th>
          <% fort_groups.each do |g| %>
            <th colspan="<%= fort_nums.size %>">
              <%= link_to(g, timeline_for_fort_path(date: date, fort: g)) %>
            </th>
          <% end %>
        </tr>
        <tr>
          <th><br/></th>
          <% fort_groups.size.times do %>
            <% fort_nums.each do |num| %>
              <th class="span1"><%= num %></th>
            <% end %>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="span2 text-center">Start</td>
          <% each_fort_code do |fcd|
            be = timeline.before_result[fcd]
            if be %>
              <td class="span1 attention text-center guild-owner">
                <strong><%= name_table[be] %></strong>
              </td>
            <% else %>
              <td class="span1 text-center"><small>-</small></td>
            <% end %>
          <% end %>
        </tr>
        <% timeline.revs.each do |rev| %>
          <tr>
            <td class="span2 text-center">
              <%= link_to(revision_to_format_time_only(rev), timeline_situation_path(date: date, rev: rev)) %>
            </td>
            <% each_fort_code do |fcd|
              state = timeline.state_for(rev, fcd)
              unless state %>
                <td class="span1 text-center"><small>-</small></td>
              <% else
                case state.first
                when :call %>
                  <td class="span1 text-center guild-owner"><%= name_table[state.last] %></td>
                <% when :stay %>
                  <td class="span1 text-center guild-stay"><small>↓</small></td>
                <% when :lose %>
                  <td class="span1 text-center guild-lose">
                    <span class="guild-pop" rel="tooltip" title="called : <%= state.last %>">
                      <small>×</small>
                    </span>
                  </td>
                <% else %>
                  <td class="span1 text-center"><small>-</small></td>
                <% end %>
                </td>
              <% end %>
            <% end %>
          </tr>
        <% end %>
        <tr>
          <td class="span2 text-center">Result</td>
          <% each_fort_code do |fcd|
            rsl = timeline.result[fcd] %>
            <% if rsl %>
              <td class="span1 attention text-center guild-owner">
                <strong><%= name_table[rsl] %></strong>
              </td>
            <% else %>
              <td class="span1 text-center"><small>-</small></td>
            <% end %>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/application/_menu_crumb.erb
<li>
  <%= link_to('Top', root_path) %> <span class="divider">&gt;</span>
</li>
<li>
  <%= link_to('Strategy Room', menu_path) %> <span class="divider">&gt;</span>
</li>

app/views/application/_sample_footer.erb
<div style="width: 500px; margin: auto;">
  <ul class="unstyled">
    <li>Server's Source Code : <a href="https://github.com/parrot-studio/gagnrath">https://github.com/parrot-studio/gagnrath</a></li>
    <li>Client's Source Code : <a href="https://github.com/parrot-studio/rogv_client">https://github.com/parrot-studio/rogv_client</a></li>
    <li>RO's Blog : <a href="http://parrot.blog21.fc2.com/">http://parrot.blog21.fc2.com/</a></li>
  </ul>
  <%=raw amazon %>
  <%=raw adsense %>
</div>
<%=raw analytics %>

app/views/application/_topnav.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="<%= root_path %>"><strong><%= site_title%></strong> <%= site_sub_title%></a>
      <ul class="nav pull-right">
        <li><%= link_to('ご利用上の注意', notes_path) %></li>
        <% unless time_locked? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Strategy Room <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to('Timeline', timeline_path) %></li>
              <li><%= link_to('Result', result_path) %></li>
            </ul>
          </li>
        <% end %>
        <% if updatable_mode? %>
          <li><%= link_to('Admin Tools', admin_path) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/application/_union_history.erb
<% unless union_history.empty? %>
  <div class="span6">
    <legend>Selected History</legend>
    <ol>
      <% union_history.reverse.each do |gs| %>
        <li><a href="#" class="history" data-list="<%= gs.join("\t") %>"><%= gs.join(' , ') %></a></li>
      <% end %>
    </ol>
    <%= link_to('Reset History', union_history_path, method: :delete) %>
  </div>
<% end %>